# @no-cookie-jar
POST http://localhost:9090/userinfo
Authorization: Bearer eyJraWQiOiJiODJiOTRiOS02NjUzLTQxNDQtYTQwOC1mNmU4NmYxY2FhOGUiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiIxMzU4MTgzNzI4MiIsImF1ZCI6InRlc3QiLCJuYmYiOjE2NzIzMTIyNTUsInNjb3BlIjpbIm9wZW5pZCIsInByb2ZpbGUiXSwiZXhwIjoxNjcyNDg1MDU1LCJpYXQiOjE2NzIzMTIyNTV9.ij5e-uH0yJkpwGf013Cmw4xEVwQAL_qJBkalXwebSX5aFVhQYOKH77w4SkYDWeMQIa0ZaPUjekBMY-heNhtOgvKMNPgHsP4lTf4eHXyuGg1I_CYNXiDY0a_YQXYruN-66i94YcEvCX1O51Tfh7zAKLlEB6Q6mB9qA0s7AqNWNce9P_hz4s-5IRtAHyOdEj0v56zt3RyER0vqo1rMwsAhBrFnafy7xPAUh3T6gs_rFfa30mpqyf0iAr_HF410eo8qT_RRS2V3kzTxm9d4PMXCKlzCmn8ufg-NrGQy9mKm-m6l9q6oxtpVKxnHqeq7UybaB1UKrtoIaqMUmCY6foASzQ