server:
  port: 9090
  error:
    include-message: always
logging:
  level:
    root: debug
spring:
  datasource:
    url: jdbc:mysql://mysql-internet-cn-north-1-335cadf679754c58.rds.jdcloud.com/camellia?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: camellia
    password: 1qAz2WSX2020