server:
  port: 9090
  error:
    include-message: always
logging:
  level:
    root: debug
spring:
  datasource:
    url: jdbc:mysql://localhost/camellia?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: camellia
    password: 1qAz2WSX2020