### Send POST request with body as parameters
POST http://localhost:9090/oauth2/token
Content-Type: application/x-www-form-urlencoded
Authorization: Basic dGVzdDoxMjM=

grant_type=client_credentials&scope=profile

###
POST http://localhost:9090/oauth2/introspect
Content-Type: application/x-www-form-urlencoded
Authorization: Basic dGVzdDoxMjM=

client_id=test&token=eyJraWQiOiIwMzBiODNhYy03NjZkLTQyN2QtYjI0YS1kNmJiY2QzYWM3Y2UiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJ0ZXN0IiwiYXVkIjoidGVzdCIsIm5iZiI6MTY5NzczNDMyNSwic2NvcGUiOlsicHJvZmlsZSJdLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjkwOTAiLCJleHAiOjE2OTc5MDcxMjUsImlhdCI6MTY5NzczNDMyNX0.c1cdfj8-pf51SJrl3nMfsNXBc5Hr8u8SOMlkQoEhwjqmB72OTLxObjh4OKTGUoWDl9qHhGV0x4n9jJaCAyvg6YTDyxyzVpY6HrwPhioYzNNhoY2wpQu2_zm62_bUJ0eDiiiZiGptHzHDZrWAGqy99NPZSz5XS1agVQYHtZdnJFXrd6dXNnI1eFUyS8oLwTgwyVpzeNjoxdcR7fGNhPKF76Rpnj5frmbpRWeGZjS_Tbn44nVnUlaDntQGGXEt2B-Db5wlBrVDfUeSdYioqyvRmI7Z6kIvWHrHmv3Hg_GjXg4BFYRMJyUJ5HnMrGQET7-s8wzdePQBUgahsCu4wK2XjarZDyTw2MfPj4PB8pXUNoSYM7ZA5qqdpCgAC-j8VQSLXNYIcYk2JPJEgb5Rtxt3NbPqE5wy6Doa51Kkh1QcE7myAc86g2wdt7dd_8SPrXQjpbpRa3EhnSc67GpkTxMO3nVWa-M2E5SVUsZyN5E5wkBNOU_1FlOU35V2LC9MbdB_-srzzOVtQQiEBhMzXsal3Ob5Ji28Wf_uwBjz5o6Fw46yj3as8Ksv1y9WfV1CwzxAYWLx0ezHM9D6prPCmYsClDNffGUhZdgcGLATyBKu87_HNodjJQkO085hr-QfgyQjImbA9__qW5s1IS7vioHXgheSH6wdEVQwzThQ5dUKIEk