POST http://localhost:9090/oauth2/introspect
Content-Type: application/x-www-form-urlencoded
Authorization: Basic YXBpOjEyMzQ=

token=eyJraWQiOiJkZTA1NzI4YS0xYmU5LTRjOWEtOTQwZi00YWVlNzUyYWRhMTkiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiIxMzU4MTgzNzI4MiIsImF1ZCI6InRlc3QiLCJuYmYiOjE2NjAyMTA1MjEsInNjb3BlIjpbIm9wZW5pZCIsInByb2ZpbGUiXSwiZXhwIjoxNjYwMzgzMzIxLCJpYXQiOjE2NjAyMTA1MjF9.p0CsN0noR7ecbUu8EIVeuPS_QCEAaZVJUvlROk0QVmKTQpRwhy2lBUe18sdl27KmHNrj1yzv_NMCT5jqgPzXshKiMAU-tbyzpnkWyl_82V54McSgp5Mk9Gl_HGXDWtMYkhH3kFIKxfovz1OuJZbAOLK0NUG8R-SCoGzofTctVazY4OpGaFCTGLmz0kTG0yR9z_-PLshzOvjkC19sq4SqORKZM7vMbsjP71FF6ygRiL1lxv21B2fhgcblLl8jh0wBIAkquBB74kYjO5zXZn3kViuVAKSfUv9XfZ1YejL6cs1Rh4ixwI-VHRsaU_Nk0o_zKIBYH_PvLP5c5qsHi6dTfQ